version: '3'

services:

  nginx:
    container_name: juanportal_nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    ports:
      - "9002:9002"
    depends_on:
      - socket
      - api
      - node
    volumes:
      - ./src/juanportal/public:/var/www/juanportal/public
    working_dir: /var/www/juanportal
    networks:
      - juanportal-network

  node:
    container_name: juanportal_node
    build:
      context: .
      dockerfile: .docker/node.dockerfile
      args:
        PROJECT_NAME: "juanportal"
    volumes:
      - ./src/juanportal/bin:/var/www/juanportal/bin
      - ./src/juanportal/components:/var/www/juanportal/components
      - ./src/juanportal/helpers:/var/www/juanportal/helpers
      - ./src/juanportal/public:/var/www/juanportal/public
      - ./src/juanportal/routes:/var/www/juanportal/routes
      - ./src/juanportal/tests:/var/www/juanportal/tests
      - ./src/juanportal/views:/var/www/juanportal/views
      - ./src/juanportal/app.ts:/var/www/juanportal/app.ts
      - ./src/juanportal/package.json:/var/www/juanportal/package.json
      - ./src/juanportal/tsconfig.json:/var/www/juanportal/tsconfig.json
      - ./src/juanportal/webpack.config.js:/var/www/juanportal/webpack.config.js
    working_dir: /var/www/juanportal
    command: bash -c "npm ci --prefer-offline --no-audit --progress=false && npm run build && npm run start"
    networks:
      - juanportal-network

  mongodb:
    container_name: juanportal_mongo
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./.docker/env/mongodb.env
    networks:
      - juanportal-network

  mongoseeder:
    container_name: juanportal_mongoseeder
    build:
      context: .
      dockerfile: .docker/mongo.seeder.dockerfile
    depends_on:
      - mongodb
    networks:
      - juanportal-network

  api:
    container_name: juanportal_api
    build:
      context: .
      dockerfile: .docker/node.dockerfile
      args:
        PROJECT_NAME: "api"
    volumes:
      - ./src/api/bin:/var/www/api/bin
      - ./src/api/controllers:/var/www/api/controllers
      - ./src/api/helpers:/var/www/api/helpers
      - ./src/api/interfaces:/var/www/api/interfaces
      - ./src/api/routes:/var/www/api/routes
      - ./src/api/tests:/var/www/api/tests
      - ./src/api/models:/var/www/api/models
      - ./src/api/schemas:/var/www/api/schemas
      - ./src/api/app.ts:/var/www/api/app.ts
      - ./src/api/package.json:/var/www/api/package.json
      - ./src/api/tsconfig.json:/var/www/api/tsconfig.json
    working_dir: /var/www/api
    command: bash -c "npm ci --prefer-offline --no-audit --progress=false && npm run build && pm2-runtime ecosystem.config.js"
    networks:
      - juanportal-network

  redis:
    container_name: juanportal_redis
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - juanportal-network

  socket:
    container_name: juanportal_socket
    build:
      context: .
      dockerfile: .docker/node.dockerfile
      args:
        PROJECT_NAME: "socket"
    volumes:
      - ./src/socket/bin:/var/www/socket
      - ./src/socket/test:/var/www/socket/test
      - ./src/socket/app.ts:/var/www/socket/app.ts
      - ./src/socket/package.json:/var/www/socket/package.json
      - ./src/socket/server.ts:/var/www/socket/server.ts
      - ./src/socket/socket.ts:/var/www/socket/socket.ts
      - ./src/socket/tsconfig.json:/var/www/socket/tsconfig.json
    working_dir: /var/www/socket
    command: bash -c "npm ci --prefer-offline --no-audit --progress=false && npm run build && npm run start"
    depends_on:
      - redis
    networks:
      - juanportal-network

networks:
  juanportal-network:
    driver: bridge
