version: '3'

services:

  nginx:
    container_name: juanportal_nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    ports:
      - "9002:9002"
    depends_on:
      - socket
      - api
      - node
    volumes:
      - ./src/juanportal:/var/www/juanportal
    working_dir: /var/www/juanportal
    networks:
      - juanportal-network

  node:
    container_name: juanportal_node
    build:
      context: .
      dockerfile: .docker/node.dockerfile
    volumes:
      - ./src/juanportal:/var/www/juanportal
    working_dir: /var/www/juanportal
    command: bash -c "npm i -s && node_modules/.bin/tsc && pm2-runtime ecosystem.config.js"
    networks:
      - juanportal-network

  mongodb:
    container_name: juanportal_mongo
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./.docker/env/mongodb.env
    networks:
      - juanportal-network

  mongoseeder:
    container_name: juanportal_mongoseeder
    build:
      context: .
      dockerfile: .docker/mongo.seeder.dockerfile
    depends_on:
      - mongodb
    networks:
      - juanportal-network

  api:
    container_name: juanportal_api
    build:
      context: .
      dockerfile: .docker/node.dockerfile
    volumes:
      - ./src/api:/var/www/api
    working_dir: /var/www/api
    command: bash -c "npm i -s && node_modules/.bin/tsc && pm2-runtime ecosystem.config.js"
    networks:
      - juanportal-network

  redis:
    container_name: juanportal_redis
    build:
      context: .
      dockerfile: .docker/redis.dockerfile
    ports:
      - "6379:6379"
    networks:
      - juanportal-network

  socket:
    container_name: juanportal_socket
    build:
      context: .
      dockerfile: .docker/python.dockerfile
    volumes:
      - ./src/socket:/var/www/socket
    working_dir: /var/www/socket
    command: bash -c "pm2-runtime --watch ecosystem.config.yml"
    depends_on:
      - redis
    #working_dir: /var/www/socket
    #command: bash -c "python app.py -p 9009"
    networks:
      - juanportal-network

networks:
  juanportal-network:
    driver: bridge
