FROM nginx:latest

# Update and install required packages
RUN     apt-get update
RUN     apt-get install vim -y

# Copy nginx config file
COPY    ./.docker/config/junaportal.conf /etc/nginx/conf.d/juanportal.conf

ENTRYPOINT ["nginx"]
CMD ["-g","daemon off;"]
