FROM mongo

COPY ./.docker/data/mongo-data-dump /mongo_data
# Profiles collection
CMD mongoimport --host monogdb --db juanportal --collection profiles --file /mongo_db/profiles.json
#CMD mongorestore --host mongodb --db juanportal /mongo_data
