name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  api-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: API Test and Coverage Check
        run: |
          cd src/api
          npm run build
          docker-compose up -d > /dev/null
          docker exec juanportal_api npm run cov
      - name: API Format Check
        run: |
          cd src/api
          npm run fmt:check
      - name: API Linter Check
        run: |
          cd src/api
          npm run lint

  client-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Client Lint Checks
        run: |
          cd src/juanportal
          npm run lint
      - name: Client Fmt Checks
        run: |
          cd src/juanportal
          npm run fmt:check
      - name: Client Tests
        run: |
          cd src/juanportal
          npm run build:all
          docker-compose up -d > /dev/null
          docker exec juanportal_node npm run testServer
          docker exec juanportal_node npm run testReact

  socket-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Socket Format Checks
        run: |
          cd src/socket
          npm run fmt:check
      - name: Socket Lint Checks
        run: |
          cd src/socket
          npm run lint
      - name: Socket Test and Coverage Check
        run: |
          cd src/socket
          npm run build
          docker-compose up -d > /dev/null
          docker exec juanportal_socket npm run cov
