name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  api-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: API Test and Coverage Check
        run: |
          npm -v
          cd src/api
          npm ci
          npm run build
          docker-compose up -d api mongodb > /dev/null
          docker exec juanportal_api npm run cov
      - name: API Format Check
        run: |
          cd src/api
          npm run fmt:check
      - name: API Linter Check
        run: |
          cd src/api
          npm run build
          npm run lint

  client-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Client Lint Checks
        run: |
          npm i -g fsevents
          cd src/juanportal
          npm i fsevents@latest -f --save-optional
          npm ci
          npm run lint
      - name: Client Fmt Checks
        run: |
          cd src/juanportal
          npm ci
          npm run fmt:check
      - name: Client Tests
        run: |
          cd src/juanportal
          echo 'MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}"' >> .env
          npm ci
          npm run build
          docker-compose up -d node redis > /dev/null
          docker exec juanportal_node npm run cov
          docker exec juanportal_node npm run test:client

  socket-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Socket Format Checks
        run: |
          cd src/socket
          npm run fmt:check
      - name: Socket Lint Checks
        run: |
          cd src/socket
          npm run lint
      - name: Socket Test and Coverage Check
        run: |
          cd src/socket
          npm ci
          npm run build
          docker-compose up -d socket > /dev/null
          docker exec juanportal_socket npm run cov

