name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: API Tests
        run: |
          docker-compose up -d > /dev/null
          sleep 200
          docker exec juanportal_api npm run test
          docker exec juanportal_api npm run test2

  client-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Client Tests
        run: |
          docker-compose up -d > /dev/null
          sleep 200
          docker-compose ps
          docker exec juanportal_node npm run test
          docker exec juanportal_node npm run testReact

  #socket-tests: