name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  api-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: API Tests
        run: |
          cd src/api
          npm run build
          docker-compose up -d > /dev/null
          docker exec juanportal_api npm run test
#      - name: API Format Check
#        run: |
##          npm run fmt:check

  client-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Client Tests
        run: |
          cd src/juanportal
          npm run build:all
          docker-compose up -d > /dev/null
          docker exec juanportal_node npm run test
          docker exec juanportal_node npm run testReact

  socket-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Socket Tests
        run: |
          cd src/socket
          npm run build
          docker-compose up -d > /dev/null
          docker exec juanportal_socket npm run test
